# Generated by Django 4.2.16 on 2024-09-17 14:20

import autoslug.fields
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('accommodation_type', models.CharField(choices=[('Room', 'Room'), ('Apartment', 'Apartment'), ('House', 'House'), ('Villa', 'Villa')], max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=10)),
                ('book_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='book_image')),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IE')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=200, populate_from='title', unique=True)),
                ('post_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
