# Generated by Django 4.2.16 on 2024-09-17 14:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpost',
            name='book_image',
        ),
        migrations.AddField(
            model_name='bookpost',
            name='booking_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='booking_image'),
        ),
    ]
